import type { Metadata } from "next";
import "./globals.css";
import React, {FC} from "react";
import HeaderComponent from "@/components/header/HeaderComponent";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode
}
const RootLayout: FC<Props> = ({children}) => {
  return (
    <html lang="en">
      <body>
        <HeaderComponent />
        {children}
      </body>
    </html>
  );
}

export default RootLayout
